export const PageRoutes = {
    LOGIN: "openapi/authorize/login?client_id=",
    AUTH_TOKEN: "openapi/authorize/code?client_id=",
    ACCESS_TOKEN: "openapi/authorize/token?grant_type="
}

export const DevicesListMaster = [
    {
        "DEVICE NAME": "Sant Niwas",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-7C-D6",
        "IP ADDRESS": "172.17.2.224",
        "PUBLIC IP ADDRESS": "172.17.2.224",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.2.6",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "TP-Link-EAP610-OUTDOOR",
        "LAST SEEN": "Aug 28, 2024 01:35 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 100,
        "yAxis": 200
    },
    {
        "DEVICE NAME": "AP-7 Indoor Batra ji Store",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-7A-61-16",
        "IP ADDRESS": "172.18.2.5",
        "PUBLIC IP ADDRESS": "172.18.2.5",
        "IPv6 ADDRESS": "-",
        "STATUS": "Connected",
        "MODEL": "EAP670(US) v1.0",
        "VERSION": "1.0.15",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": "8day(s) 9m 6s",
        "MEM. USAGE": "63%",
        "CPU USAGE": "12%",
        "CLIENTS": "4",
        "DOWN": "30.75 GB",
        "UP": "10.86 GB",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "Auto(11)\/25 dBm",
        "RADIO5G": "Auto(36)\/Auto",
        "RADIO6G": "-",
        "2G CLIENTS": "1",
        "5G CLIENTS": "3(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "50-91-E3-7A-61-16;56-91-E3-7A-61-16;5A-91-E3-7A-61-16;5E-91-E3-7A-61-16;62-91-E3-7A-61-16;50-91-E3-7A-61-17;56-91-E3-7A-61-17;5A-91-E3-7A-61-17;5E-91-E3-7A-61-17;62-91-E3-7A-61-17",
        "TX RATE": "8.87 KB \/ s",
        "RX RATE": "1.66 KB \/ s",
        "CHANNEL": "11(2.4G);36(5G)",
        "CH. UTIL. 2G": "49%",
        "CH. UTIL. 5G": "6%",
        "CH. UTIL. 6G": "-",
        "TAGS": "TP-Link-EAP610-OUTDOOR",
        "LAST SEEN": "Oct 10, 2024 05:25 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 101,
        "yAxis": 201
    },
    {
        "DEVICE NAME": "AP-60 FREE",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-7C-08",
        "IP ADDRESS": "172.16.29.21",
        "PUBLIC IP ADDRESS": "172.16.29.21",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.2.6",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "TP-Link-EAP610-OUTDOOR",
        "LAST SEEN": "Sep 12, 2024 11:49 AM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 102,
        "yAxis": 202
    },
    {
        "DEVICE NAME": "AP-67 FREE",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-FF-7B-C4",
        "IP ADDRESS": "172.18.2.115",
        "PUBLIC IP ADDRESS": "172.18.2.115",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "TP-Link-EAP610-OUTDOOR",
        "LAST SEEN": "Sep 22, 2024 11:18 AM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 103,
        "yAxis": 203
    },
    {
        "DEVICE NAME": "AP-70 FREE",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-76-92",
        "IP ADDRESS": "172.18.2.145",
        "PUBLIC IP ADDRESS": "172.18.2.145",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "TP-Link-EAP610-OUTDOOR",
        "LAST SEEN": "Sep 22, 2024 12:43 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 104,
        "yAxis": 204
    },
    {
        "DEVICE NAME": "AP-9 Indoor Server Room",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-60-EA-BC",
        "IP ADDRESS": "172.18.2.4",
        "PUBLIC IP ADDRESS": "172.18.2.4",
        "IPv6 ADDRESS": "-",
        "STATUS": "Connected",
        "MODEL": "EAP670(US) v1.0",
        "VERSION": "1.0.15",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": "8day(s) 8m 45s",
        "MEM. USAGE": "63%",
        "CPU USAGE": "11%",
        "CLIENTS": "1",
        "DOWN": "38.03 GB",
        "UP": "12.43 GB",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "Auto(6)\/Auto",
        "RADIO5G": "Auto(36)\/Auto",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "1(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "50-91-E3-60-EA-BC;56-91-E3-60-EA-BC;5A-91-E3-60-EA-BC;5E-91-E3-60-EA-BC;62-91-E3-60-EA-BC;50-91-E3-60-EA-BD;56-91-E3-60-EA-BD;5A-91-E3-60-EA-BD;5E-91-E3-60-EA-BD;62-91-E3-60-EA-BD",
        "TX RATE": "5.84 KB \/ s",
        "RX RATE": "0 Bytes \/ s",
        "CHANNEL": "6(2.4G);36(5G)",
        "CH. UTIL. 2G": "21%",
        "CH. UTIL. 5G": "6%",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Oct 10, 2024 05:25 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 105,
        "yAxis": 205
    },
    {
        "DEVICE NAME": "AP-10",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-FF-6F-DE",
        "IP ADDRESS": "172.16.29.62",
        "PUBLIC IP ADDRESS": "172.16.29.62",
        "IPv6 ADDRESS": "-",
        "STATUS": "Connected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.2.6",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": "1day(s) 20h 54m 22s",
        "MEM. USAGE": "73%",
        "CPU USAGE": "4%",
        "CLIENTS": "1",
        "DOWN": "11.58 GB",
        "UP": "1.38 GB",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "Auto(1)\/Auto",
        "RADIO5G": "Auto(161)\/Auto",
        "RADIO6G": "-",
        "2G CLIENTS": "1",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "50-91-E3-FF-6F-DE;56-91-E3-FF-6F-DE;5A-91-E3-FF-6F-DE;5E-91-E3-FF-6F-DE;62-91-E3-FF-6F-DE;50-91-E3-FF-6F-DF;56-91-E3-FF-6F-DF;5A-91-E3-FF-6F-DF;5E-91-E3-FF-6F-DF;62-91-E3-FF-6F-DF",
        "TX RATE": "290.75 KB \/ s",
        "RX RATE": "4.72 KB \/ s",
        "CHANNEL": "1(2.4G);161(5G)",
        "CH. UTIL. 2G": "48%",
        "CH. UTIL. 5G": "7%",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Oct 10, 2024 05:25 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 106,
        "yAxis": 206
    },
    {
        "DEVICE NAME": "AP-46",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-76-A2",
        "IP ADDRESS": "172.18.1.4",
        "PUBLIC IP ADDRESS": "172.18.1.4",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 13, 2024 01:24 AM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 107,
        "yAxis": 207
    },
    {
        "DEVICE NAME": "AP-16",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "78-8C-B5-2A-28-DE",
        "IP ADDRESS": "172.18.1.14",
        "PUBLIC IP ADDRESS": "172.18.1.14",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.2.5",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 13, 2024 01:32 AM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 108,
        "yAxis": 208
    },
    {
        "DEVICE NAME": "Bhakti-Niwas-AP",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-7B-22",
        "IP ADDRESS": "172.18.1.70",
        "PUBLIC IP ADDRESS": "172.18.1.70",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 13, 2024 01:09 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 109,
        "yAxis": 209
    },
    {
        "DEVICE NAME": "AP-Unknown1",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-76-1C",
        "IP ADDRESS": "172.18.1.20",
        "PUBLIC IP ADDRESS": "172.18.1.20",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 13, 2024 01:53 AM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 110,
        "yAxis": 210
    },
    {
        "DEVICE NAME": "AP-57",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-79-2C",
        "IP ADDRESS": "172.18.1.22",
        "PUBLIC IP ADDRESS": "172.18.1.22",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.2.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 13, 2024 01:47 AM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 111,
        "yAxis": 211
    },
    {
        "DEVICE NAME": "AP-04 Welding Workshop",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "9C-53-22-B9-FF-B8",
        "IP ADDRESS": "172.18.2.67",
        "PUBLIC IP ADDRESS": "172.18.2.67",
        "IPv6 ADDRESS": "-",
        "STATUS": "Connected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.2.6",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": "2h 26m 12s",
        "MEM. USAGE": "66%",
        "CPU USAGE": "3%",
        "CLIENTS": "4",
        "DOWN": "322.58 MB",
        "UP": "54.79 MB",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "Auto(11)\/Auto",
        "RADIO5G": "Auto(157)\/Auto",
        "RADIO6G": "-",
        "2G CLIENTS": "2",
        "5G CLIENTS": "2(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "9C-53-22-B9-FF-B8;A2-53-22-B9-FF-B8;A6-53-22-B9-FF-B8;AA-53-22-B9-FF-B8;AE-53-22-B9-FF-B8;9C-53-22-B9-FF-B9;A2-53-22-B9-FF-B9;A6-53-22-B9-FF-B9;AA-53-22-B9-FF-B9;AE-53-22-B9-FF-B9",
        "TX RATE": "12.48 KB \/ s",
        "RX RATE": "1.02 KB \/ s",
        "CHANNEL": "11(2.4G);157(5G)",
        "CH. UTIL. 2G": "53%",
        "CH. UTIL. 5G": "4%",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Oct 10, 2024 05:25 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 112,
        "yAxis": 212
    },
    {
        "DEVICE NAME": "AP-Unknown2",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-7B-1A",
        "IP ADDRESS": "172.18.1.26",
        "PUBLIC IP ADDRESS": "172.18.1.26",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.2.6",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 13, 2024 01:54 AM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 113,
        "yAxis": 213
    },
    {
        "DEVICE NAME": "AP-Unknown-3",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-7C-0C",
        "IP ADDRESS": "172.18.1.25",
        "PUBLIC IP ADDRESS": "172.18.1.25",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 13, 2024 01:57 AM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 114,
        "yAxis": 214
    },
    {
        "DEVICE NAME": "AP-22",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-FF-7B-BC",
        "IP ADDRESS": "172.18.1.27",
        "PUBLIC IP ADDRESS": "172.18.1.27",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 13, 2024 01:57 AM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 115,
        "yAxis": 215
    },
    {
        "DEVICE NAME": "AP-8 Layout Office(ATM)",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-7D-70",
        "IP ADDRESS": "172.18.2.63",
        "PUBLIC IP ADDRESS": "172.18.2.63",
        "IPv6 ADDRESS": "-",
        "STATUS": "Connected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.2.6",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": "8day(s) 9m 13s",
        "MEM. USAGE": "73%",
        "CPU USAGE": "6%",
        "CLIENTS": "7",
        "DOWN": "68.43 GB",
        "UP": "12.84 GB",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "Auto(1)\/Auto",
        "RADIO5G": "Auto(44)\/Auto",
        "RADIO6G": "-",
        "2G CLIENTS": "5",
        "5G CLIENTS": "2(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "50-91-E3-1B-7D-70;56-91-E3-1B-7D-70;5A-91-E3-1B-7D-70;5E-91-E3-1B-7D-70;62-91-E3-1B-7D-70;50-91-E3-1B-7D-71;56-91-E3-1B-7D-71;5A-91-E3-1B-7D-71;5E-91-E3-1B-7D-71;62-91-E3-1B-7D-71",
        "TX RATE": "3.93 KB \/ s",
        "RX RATE": "28 Bytes \/ s",
        "CHANNEL": "1(2.4G);44(5G)",
        "CH. UTIL. 2G": "43%",
        "CH. UTIL. 5G": "5%",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Oct 10, 2024 05:25 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 116,
        "yAxis": 216
    },
    {
        "DEVICE NAME": "AP-1 Meerut canteen",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-76-EA",
        "IP ADDRESS": "172.18.2.84",
        "PUBLIC IP ADDRESS": "172.18.2.84",
        "IPv6 ADDRESS": "-",
        "STATUS": "Connected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.2.6",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": "10h 24m 17s",
        "MEM. USAGE": "69%",
        "CPU USAGE": "3%",
        "CLIENTS": "5",
        "DOWN": "6.0 GB",
        "UP": "571.61 MB",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "Auto(1)\/Auto",
        "RADIO5G": "Auto(149)\/Auto",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "5(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "50-91-E3-1B-76-EA;56-91-E3-1B-76-EA;5A-91-E3-1B-76-EA;5E-91-E3-1B-76-EA;62-91-E3-1B-76-EA;50-91-E3-1B-76-EB;56-91-E3-1B-76-EB;5A-91-E3-1B-76-EB;5E-91-E3-1B-76-EB;62-91-E3-1B-76-EB",
        "TX RATE": "920 Bytes \/ s",
        "RX RATE": "14 Bytes \/ s",
        "CHANNEL": "1(2.4G);149(5G)",
        "CH. UTIL. 2G": "0%",
        "CH. UTIL. 5G": "5%",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Oct 10, 2024 05:25 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 117,
        "yAxis": 217
    },
    {
        "DEVICE NAME": "AP-30",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-FF-76-04",
        "IP ADDRESS": "172.18.1.63",
        "PUBLIC IP ADDRESS": "172.18.1.63",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 13, 2024 01:02 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 118,
        "yAxis": 218
    },
    {
        "DEVICE NAME": "AP-47",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-7D-48",
        "IP ADDRESS": "172.18.1.73",
        "PUBLIC IP ADDRESS": "172.18.1.73",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.2.6",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 13, 2024 01:09 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 119,
        "yAxis": 219
    },
    {
        "DEVICE NAME": "AP-45",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-6E-8C",
        "IP ADDRESS": "172.18.1.80",
        "PUBLIC IP ADDRESS": "172.18.1.80",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.2.6",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 13, 2024 01:24 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 120,
        "yAxis": 220
    },
    {
        "DEVICE NAME": "AP-Unknown6",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-6E-8E",
        "IP ADDRESS": "172.18.1.78",
        "PUBLIC IP ADDRESS": "172.18.1.78",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.2.6",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 13, 2024 01:23 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 121,
        "yAxis": 221
    },
    {
        "DEVICE NAME": "AP-68",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-7C-06",
        "IP ADDRESS": "172.18.1.79",
        "PUBLIC IP ADDRESS": "172.18.1.79",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 13, 2024 01:24 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 122,
        "yAxis": 222
    },
    {
        "DEVICE NAME": "AP-Unknown5",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "9C-53-22-B9-F9-CC",
        "IP ADDRESS": "172.18.1.81",
        "PUBLIC IP ADDRESS": "172.18.1.81",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.2.6",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 13, 2024 01:24 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 123,
        "yAxis": 223
    },
    {
        "DEVICE NAME": "AP-53",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-75-DC",
        "IP ADDRESS": "172.18.1.86",
        "PUBLIC IP ADDRESS": "172.18.1.86",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.2.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 13, 2024 01:49 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 124,
        "yAxis": 224
    },
    {
        "DEVICE NAME": "AP-21",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-75-FA",
        "IP ADDRESS": "172.18.1.85",
        "PUBLIC IP ADDRESS": "172.18.1.85",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 13, 2024 01:38 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 125,
        "yAxis": 225
    },
    {
        "DEVICE NAME": "AP-Unknown7",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-76-20",
        "IP ADDRESS": "172.18.1.84",
        "PUBLIC IP ADDRESS": "172.18.1.84",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 13, 2024 01:38 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 126,
        "yAxis": 226
    },
    {
        "DEVICE NAME": "AP-69",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-76-28",
        "IP ADDRESS": "172.18.1.83",
        "PUBLIC IP ADDRESS": "172.18.1.83",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 13, 2024 01:38 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 127,
        "yAxis": 227
    },
    {
        "DEVICE NAME": "AP-Unknown9",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "9C-53-22-B9-F7-2E",
        "IP ADDRESS": "172.18.1.87",
        "PUBLIC IP ADDRESS": "172.18.1.87",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.2.6",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 13, 2024 03:24 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 128,
        "yAxis": 228
    },
    {
        "DEVICE NAME": "AP-Unknown8",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-7B-24",
        "IP ADDRESS": "172.18.1.88",
        "PUBLIC IP ADDRESS": "172.18.1.88",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 13, 2024 03:24 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 129,
        "yAxis": 229
    },
    {
        "DEVICE NAME": "AP-11(ICT Store)",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-16-F4-7C",
        "IP ADDRESS": "172.18.2.10",
        "PUBLIC IP ADDRESS": "172.18.2.10",
        "IPv6 ADDRESS": "-",
        "STATUS": "Connected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.2.6",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": "2h 25m 11s",
        "MEM. USAGE": "66%",
        "CPU USAGE": "17%",
        "CLIENTS": "2",
        "DOWN": "1.05 GB",
        "UP": "77.43 MB",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "Auto(11)\/Auto",
        "RADIO5G": "Auto(44)\/Auto",
        "RADIO6G": "-",
        "2G CLIENTS": "2",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "50-91-E3-16-F4-7C;56-91-E3-16-F4-7C;5A-91-E3-16-F4-7C;5E-91-E3-16-F4-7C;62-91-E3-16-F4-7C;50-91-E3-16-F4-7D;56-91-E3-16-F4-7D;5A-91-E3-16-F4-7D;5E-91-E3-16-F4-7D;62-91-E3-16-F4-7D",
        "TX RATE": "474.9 KB \/ s",
        "RX RATE": "47.74 KB \/ s",
        "CHANNEL": "11(2.4G);44(5G)",
        "CH. UTIL. 2G": "52%",
        "CH. UTIL. 5G": "2%",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Oct 10, 2024 05:25 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 130,
        "yAxis": 230
    },
    {
        "DEVICE NAME": "AP-63",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-7D-3A",
        "IP ADDRESS": "172.18.1.15",
        "PUBLIC IP ADDRESS": "172.18.1.15",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 13, 2024 03:24 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 131,
        "yAxis": 231
    },
    {
        "DEVICE NAME": "AP-9",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-FF-75-CA",
        "IP ADDRESS": "172.16.29.50",
        "PUBLIC IP ADDRESS": "172.16.29.50",
        "IPv6 ADDRESS": "-",
        "STATUS": "Connected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.2.6",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": "1day(s) 20h 52m 13s",
        "MEM. USAGE": "70%",
        "CPU USAGE": "15%",
        "CLIENTS": "5",
        "DOWN": "44.14 GB",
        "UP": "3.75 GB",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "Auto(11)\/Auto",
        "RADIO5G": "Auto(149)\/Auto",
        "RADIO6G": "-",
        "2G CLIENTS": "1",
        "5G CLIENTS": "4(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "50-91-E3-FF-75-CA;56-91-E3-FF-75-CA;5A-91-E3-FF-75-CA;5E-91-E3-FF-75-CA;62-91-E3-FF-75-CA;50-91-E3-FF-75-CB;56-91-E3-FF-75-CB;5A-91-E3-FF-75-CB;5E-91-E3-FF-75-CB;62-91-E3-FF-75-CB",
        "TX RATE": "229.81 KB \/ s",
        "RX RATE": "15.1 KB \/ s",
        "CHANNEL": "11(2.4G);149(5G)",
        "CH. UTIL. 2G": "54%",
        "CH. UTIL. 5G": "29%",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Oct 10, 2024 05:25 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 132,
        "yAxis": 232
    },
    {
        "DEVICE NAME": "AP-Unknown10",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "9C-53-22-B9-F7-58",
        "IP ADDRESS": "172.18.1.98",
        "PUBLIC IP ADDRESS": "172.18.1.98",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 13, 2024 03:25 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 133,
        "yAxis": 233
    },
    {
        "DEVICE NAME": "AP-Unkown11",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-7D-74",
        "IP ADDRESS": "172.18.1.97",
        "PUBLIC IP ADDRESS": "172.18.1.97",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.2.5",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 13, 2024 03:23 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 134,
        "yAxis": 234
    },
    {
        "DEVICE NAME": "AP-59",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-FF-73-C8",
        "IP ADDRESS": "172.18.1.96",
        "PUBLIC IP ADDRESS": "172.18.1.96",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.2.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 13, 2024 03:24 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 135,
        "yAxis": 235
    },
    {
        "DEVICE NAME": "AP-66",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-76-1A",
        "IP ADDRESS": "172.18.1.37",
        "PUBLIC IP ADDRESS": "172.18.1.37",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.2.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 13, 2024 03:47 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 136,
        "yAxis": 236
    },
    {
        "DEVICE NAME": "AP-Unknown13",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-7A-C0",
        "IP ADDRESS": "172.18.1.36",
        "PUBLIC IP ADDRESS": "172.18.1.36",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.2.6",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 13, 2024 03:46 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 137,
        "yAxis": 237
    },
    {
        "DEVICE NAME": "AP-Unknown12",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "78-8C-B5-2A-21-C2",
        "IP ADDRESS": "172.18.1.82",
        "PUBLIC IP ADDRESS": "172.18.1.82",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 13, 2024 03:45 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 138,
        "yAxis": 238
    },
    {
        "DEVICE NAME": "AP-20",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-7C-34",
        "IP ADDRESS": "172.18.1.111",
        "PUBLIC IP ADDRESS": "172.18.1.111",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 13, 2024 04:26 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 139,
        "yAxis": 239
    },
    {
        "DEVICE NAME": "AP-40",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-16-F4-78",
        "IP ADDRESS": "172.18.1.112",
        "PUBLIC IP ADDRESS": "172.18.1.112",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 13, 2024 04:34 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 140,
        "yAxis": 240
    },
    {
        "DEVICE NAME": "AP-39",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-79-22",
        "IP ADDRESS": "172.18.2.76",
        "PUBLIC IP ADDRESS": "172.18.2.76",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.2.6",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 04:39 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 141,
        "yAxis": 241
    },
    {
        "DEVICE NAME": "AP-19",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "9C-53-22-B9-FE-F2",
        "IP ADDRESS": "172.18.2.77",
        "PUBLIC IP ADDRESS": "172.18.2.77",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 11:45 AM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 142,
        "yAxis": 242
    },
    {
        "DEVICE NAME": "AP-36",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-7D-78",
        "IP ADDRESS": "172.18.2.81",
        "PUBLIC IP ADDRESS": "172.18.2.81",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 10:50 AM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 143,
        "yAxis": 243
    },
    {
        "DEVICE NAME": "AP-18",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "9C-53-22-B9-F5-AA",
        "IP ADDRESS": "172.18.2.16",
        "PUBLIC IP ADDRESS": "172.18.2.16",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 10:52 AM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 144,
        "yAxis": 244
    },
    {
        "DEVICE NAME": "A-42",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-7A-D4",
        "IP ADDRESS": "172.18.2.97",
        "PUBLIC IP ADDRESS": "172.18.2.97",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 11:00 AM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 145,
        "yAxis": 245
    },
    {
        "DEVICE NAME": "AP-27",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-FF-75-D6",
        "IP ADDRESS": "172.18.2.100",
        "PUBLIC IP ADDRESS": "172.18.2.100",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 11:30 AM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 146,
        "yAxis": 246
    },
    {
        "DEVICE NAME": "AP_28",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-7B-1E",
        "IP ADDRESS": "172.18.2.78",
        "PUBLIC IP ADDRESS": "172.18.2.78",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 11:35 AM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 147,
        "yAxis": 247
    },
    {
        "DEVICE NAME": "AP-23",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-FF-7B-9E",
        "IP ADDRESS": "172.18.2.93",
        "PUBLIC IP ADDRESS": "172.18.2.93",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 11:37 AM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 148,
        "yAxis": 248
    },
    {
        "DEVICE NAME": "AP-55",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-76-0E",
        "IP ADDRESS": "172.18.2.80",
        "PUBLIC IP ADDRESS": "172.18.2.80",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.2.6",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 11:52 AM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 149,
        "yAxis": 249
    },
    {
        "DEVICE NAME": "AP-38",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-7D-7E",
        "IP ADDRESS": "172.18.2.117",
        "PUBLIC IP ADDRESS": "172.18.2.117",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 12:05 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 150,
        "yAxis": 250
    },
    {
        "DEVICE NAME": "AP-Bhakti-Niwas",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "9C-53-22-B9-F8-A6",
        "IP ADDRESS": "172.18.2.118",
        "PUBLIC IP ADDRESS": "172.18.2.118",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 12:49 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 151,
        "yAxis": 251
    },
    {
        "DEVICE NAME": "AP-47",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-78-4A",
        "IP ADDRESS": "172.18.2.67",
        "PUBLIC IP ADDRESS": "172.18.2.67",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.2.6",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 12:11 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 152,
        "yAxis": 252
    },
    {
        "DEVICE NAME": "AP-64",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-7A-EE",
        "IP ADDRESS": "172.18.2.70",
        "PUBLIC IP ADDRESS": "172.18.2.70",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.2.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 12:12 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 153,
        "yAxis": 253
    },
    {
        "DEVICE NAME": "AP-34",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-78-8A",
        "IP ADDRESS": "172.18.2.130",
        "PUBLIC IP ADDRESS": "172.18.2.130",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 12:31 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 154,
        "yAxis": 254
    },
    {
        "DEVICE NAME": "AP-35",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-7C-A6",
        "IP ADDRESS": "172.18.2.132",
        "PUBLIC IP ADDRESS": "172.18.2.132",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 12:32 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 155,
        "yAxis": 255
    },
    {
        "DEVICE NAME": "AP-13",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-FF-73-FE",
        "IP ADDRESS": "172.18.2.131",
        "PUBLIC IP ADDRESS": "172.18.2.131",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 12:32 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 156,
        "yAxis": 256
    },
    {
        "DEVICE NAME": "AP-33",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-7C-F8",
        "IP ADDRESS": "172.18.2.123",
        "PUBLIC IP ADDRESS": "172.18.2.123",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 12:31 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 157,
        "yAxis": 257
    },
    {
        "DEVICE NAME": "AP-37",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-7C-80",
        "IP ADDRESS": "172.18.2.113",
        "PUBLIC IP ADDRESS": "172.18.2.113",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 12:29 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 158,
        "yAxis": 258
    },
    {
        "DEVICE NAME": "AP-15",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-7C-F6",
        "IP ADDRESS": "172.18.2.145",
        "PUBLIC IP ADDRESS": "172.18.2.145",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.2.5",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Oct 06, 2024 03:08 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 159,
        "yAxis": 259
    },
    {
        "DEVICE NAME": "AP-48",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-76-2E",
        "IP ADDRESS": "172.18.2.105",
        "PUBLIC IP ADDRESS": "172.18.2.105",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.2.6",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 12:32 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 160,
        "yAxis": 260
    },
    {
        "DEVICE NAME": "AP-26",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-7B-18",
        "IP ADDRESS": "172.18.2.125",
        "PUBLIC IP ADDRESS": "172.18.2.125",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 12:38 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 161,
        "yAxis": 261
    },
    {
        "DEVICE NAME": "AP-61",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-7C-12",
        "IP ADDRESS": "172.18.2.107",
        "PUBLIC IP ADDRESS": "172.18.2.107",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 12:44 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 162,
        "yAxis": 262
    },
    {
        "DEVICE NAME": "AP-62",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-78-8C",
        "IP ADDRESS": "172.18.2.75",
        "PUBLIC IP ADDRESS": "172.18.2.75",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 12:47 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 163,
        "yAxis": 263
    },
    {
        "DEVICE NAME": "AP-17",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "9C-A2-F4-4F-A5-52",
        "IP ADDRESS": "172.18.2.82",
        "PUBLIC IP ADDRESS": "172.18.2.82",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.2.5",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 12:52 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 164,
        "yAxis": 264
    },
    {
        "DEVICE NAME": "AP-15-1",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-76-AC",
        "IP ADDRESS": "172.18.2.31",
        "PUBLIC IP ADDRESS": "172.18.2.31",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 12:57 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 165,
        "yAxis": 265
    },
    {
        "DEVICE NAME": "AP-65",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-7C-CE",
        "IP ADDRESS": "172.18.2.22",
        "PUBLIC IP ADDRESS": "172.18.2.22",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.2.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 12:57 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 166,
        "yAxis": 266
    },
    {
        "DEVICE NAME": "AP-29",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-1B-7A-F4",
        "IP ADDRESS": "172.18.2.13",
        "PUBLIC IP ADDRESS": "172.18.2.13",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP610-Outdoor(US) v1.0",
        "VERSION": "1.1.3",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 12:57 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 167,
        "yAxis": 267
    },
    {
        "DEVICE NAME": "AP-15-Indoor dispensary",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-60-EB-0A",
        "IP ADDRESS": "172.18.2.65",
        "PUBLIC IP ADDRESS": "172.18.2.65",
        "IPv6 ADDRESS": "-",
        "STATUS": "Connected",
        "MODEL": "EAP670(US) v1.0",
        "VERSION": "1.0.15",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": "7day(s) 8h 42m 11s",
        "MEM. USAGE": "66%",
        "CPU USAGE": "10%",
        "CLIENTS": "5",
        "DOWN": "81.52 GB",
        "UP": "26.24 GB",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "Auto(1)\/Auto",
        "RADIO5G": "Auto(149)\/Auto",
        "RADIO6G": "-",
        "2G CLIENTS": "5",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "50-91-E3-60-EB-0A;56-91-E3-60-EB-0A;5A-91-E3-60-EB-0A;5E-91-E3-60-EB-0A;62-91-E3-60-EB-0A;50-91-E3-60-EB-0B;56-91-E3-60-EB-0B;5A-91-E3-60-EB-0B;5E-91-E3-60-EB-0B;62-91-E3-60-EB-0B",
        "TX RATE": "17.16 KB \/ s",
        "RX RATE": "1.44 KB \/ s",
        "CHANNEL": "1(2.4G);149(5G)",
        "CH. UTIL. 2G": "42%",
        "CH. UTIL. 5G": "2%",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Oct 10, 2024 05:25 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 168,
        "yAxis": 268
    },
    {
        "DEVICE NAME": "AP-12-Indoor",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-60-E7-CA",
        "IP ADDRESS": "172.18.2.148",
        "PUBLIC IP ADDRESS": "172.18.2.148",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP670(US) v1.0",
        "VERSION": "1.0.9",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 12:59 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 169,
        "yAxis": 269
    },
    {
        "DEVICE NAME": "AP-4-Indoor",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-60-EA-F2",
        "IP ADDRESS": "172.18.2.151",
        "PUBLIC IP ADDRESS": "172.18.2.151",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP670(US) v1.0",
        "VERSION": "1.0.9",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 01:14 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 170,
        "yAxis": 270
    },
    {
        "DEVICE NAME": "AP-13-Indoor",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-60-EB-1C",
        "IP ADDRESS": "172.18.2.48",
        "PUBLIC IP ADDRESS": "172.18.2.48",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP670(US) v1.0",
        "VERSION": "1.0.9",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 01:14 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 171,
        "yAxis": 271
    },
    {
        "DEVICE NAME": "AP-5-INDOOR",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-60-EB-16",
        "IP ADDRESS": "172.18.2.155",
        "PUBLIC IP ADDRESS": "172.18.2.155",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP670(US) v1.0",
        "VERSION": "1.0.9",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 01:07 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 172,
        "yAxis": 272
    },
    {
        "DEVICE NAME": "AP-SNCF1",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "30-DE-4B-49-F3-66",
        "IP ADDRESS": "172.18.2.153",
        "PUBLIC IP ADDRESS": "172.18.2.153",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP670(US) v1.0",
        "VERSION": "1.0.15",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 01:14 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 173,
        "yAxis": 273
    },
    {
        "DEVICE NAME": "AP-10-Indoor",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "30-DE-4B-49-F3-BA",
        "IP ADDRESS": "172.18.2.152",
        "PUBLIC IP ADDRESS": "172.18.2.152",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP670(US) v1.0",
        "VERSION": "1.0.6",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 01:14 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 174,
        "yAxis": 274
    },
    {
        "DEVICE NAME": "AP1-ICT",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "30-DE-4B-49-EF-BC",
        "IP ADDRESS": "172.18.2.156",
        "PUBLIC IP ADDRESS": "172.18.2.156",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP670(US) v1.0",
        "VERSION": "1.0.14",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 01:22 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 175,
        "yAxis": 275
    },
    {
        "DEVICE NAME": "AP-14-Indoor",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "40-ED-00-7D-68-D8",
        "IP ADDRESS": "172.18.2.158",
        "PUBLIC IP ADDRESS": "172.18.2.158",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP670(US) v1.0",
        "VERSION": "1.0.9",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 01:36 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 176,
        "yAxis": 276
    },
    {
        "DEVICE NAME": "AP-11-Indoor",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "50-91-E3-60-E6-D8",
        "IP ADDRESS": "172.18.2.157",
        "PUBLIC IP ADDRESS": "172.18.2.157",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP670(US) v1.0",
        "VERSION": "1.0.9",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 01:35 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 177,
        "yAxis": 277
    },
    {
        "DEVICE NAME": "AP-6-Indoor",
        "SERIAL NUMBER": " ",
        "MAC ADDRESS": "40-ED-00-C6-D5-96",
        "IP ADDRESS": "172.18.2.66",
        "PUBLIC IP ADDRESS": "172.18.2.66",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "EAP670(US) v1.0",
        "VERSION": "1.0.9",
        "UPLINK": "-",
        "DOWNLINK": "0",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "0(Root AP)",
        "WLAN GROUP": "WLAN_GROUP",
        "OVERRIDE": "0\/5",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "0",
        "5G CLIENTS": "0(5GHz-1),0(5GHz-2)",
        "6G CLIENTS": "0",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "-",
        "LAST SEEN": "Sep 22, 2024 01:34 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 178,
        "yAxis": 278
    },
    {
        "DEVICE NAME": "SWITCH-1 SERVER ROOM",
        "SERIAL NUMBER": "22343F8003172",
        "MAC ADDRESS": "5C-62-8B-73-A1-DB",
        "IP ADDRESS": "172.17.25.192",
        "PUBLIC IP ADDRESS": "172.17.25.192",
        "IPv6 ADDRESS": "-",
        "STATUS": "Disconnected",
        "MODEL": "SG2210P v5.20",
        "VERSION": "5.20.1",
        "UPLINK": "-",
        "DOWNLINK": "-",
        "UPTIME": " ",
        "MEM. USAGE": "-",
        "CPU USAGE": "-",
        "CLIENTS": "0",
        "DOWN": "0.0",
        "UP": "0.0",
        "LOOPBACK": "-",
        "HOP": "-",
        "WLAN GROUP": "-",
        "OVERRIDE": "-",
        "RADIO2G": "-",
        "RADIO5G": "-",
        "RADIO6G": "-",
        "2G CLIENTS": "-",
        "5G CLIENTS": "-",
        "6G CLIENTS": "-",
        "BSSID": "-",
        "TX RATE": "-",
        "RX RATE": "-",
        "CHANNEL": "-",
        "CH. UTIL. 2G": "-",
        "CH. UTIL. 5G": "-",
        "CH. UTIL. 6G": "-",
        "TAGS": "POE-SWITCH",
        "LAST SEEN": "Aug 28, 2024 09:28 PM",
        "STACK NAME": "-",
        "SITE NAME": "SNM_77_WIFI_SYSTEM",
        "xAxis": 179,
        "yAxis": 279
    }
]